import type { LucideIcon } from "lucide-react";
import {
  Bike,
  BookOpen,
  Brain,
  Camera,
  Cat,
  Code,
  Coffee,
  Cpu,
  Database,
  Dumbbell,
  Film,
  Gamepad2,
  GitBranch,
  Globe,
  Headphones,
  Heart,
  Laptop,
  Layers,
  Mic,
  Mountain,
  Music,
  Package,
  Paintbrush,
  Palette,
  PenLine,
  Plane,
  Puzzle,
  Sparkles,
  Terminal,
  Trees,
  Utensils,
  Video,
  Wrench,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  bike: Bike,
  motorbike: Bike,
  book: BookOpen,
  bookopen: BookOpen,
  brain: Brain,
  camera: Camera,
  cat: Cat,
  code: Code,
  coffee: Coffee,
  cpu: Cpu,
  database: Database,
  dumbbell: Dumbbell,
  film: Film,
  gamepad: Gamepad2,
  "git-branch": GitBranch,
  gitbranch: GitBranch,
  globe: Globe,
  headphones: Headphones,
  heart: Heart,
  laptop: Laptop,
  layers: Layers,
  mic: Mic,
  mountain: Mountain,
  music: Music,
  package: Package,
  paintbrush: Paintbrush,
  palette: Palette,
  pen: PenLine,
  plane: Plane,
  puzzle: Puzzle,
  sparkles: Sparkles,
  terminal: Terminal,
  tree: Trees,
  trees: Trees,
  utensils: Utensils,
  video: Video,
  wrench: Wrench,
};

const FALLBACK_ICON = Sparkles;

export const getProfileIntroIcon = (iconKey: string): LucideIcon => {
  const normalized = iconKey.trim().toLowerCase().replace(/\s+/g, "-");
  return ICON_MAP[normalized] ?? FALLBACK_ICON;
};
